# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d620fcb1e6b5d52d8306f1c4ec2fe81a8b1b7a186d43d4c1be8b493664c9329cf007a19aabfd67e00357c25f28f9dbc62ab10f118e63cbf04c4e375c7d3f085

test:
  secret_key_base: 0537c5d1d7ae4ca8cdc9721f40a99d966ef9de8a1c781d37b3fdadc96c3868094ab1fcd8c9c27c8d81a2d6eefe7101ac40e582a8ceab67469416be954d3e710a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
